package template

type ImportedPackage struct {
	Name  string
	Alias string
}

func (tp *TemplateParser) ParsePackages(name string, importedPackages []*ImportedPackage) (string, error) {
	return execTmpl(`// Code generated by "repogen"; DO NOT EDIT. 
	package {{.Name}}
	import (
		{{range .Imported}} {{if .Alias}}{{.Alias}} {{end}}"{{.Name}}"
		{{end}})`, map[string]interface{}{
		"Name":     name,
		"Imported": importedPackages,
	})
}
